### ISSUE TITLE
Upgrade ktor, ktor release version 3.0.1 has been released

### ISSUE THREAD

**Issue by sceneren** [programadorthi/kotlin-routing#7]
When I upgraded ktor to 3.0.1, an error occurred

```
java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Ljava/lang/String;)V in class Lio/ktor/util/AttributeKey; or its super classes (declaration of 'io.ktor.util.AttributeKey' appears in /data/app/~~MltMQiMNSw1PH396ktLhmA==/com.saio.mutv-mEYLGCdOjbcZos4Z_x-yxA==/base.apk!classes25.dex)
               at dev.programadorthi.routing.core.Routing.<clinit>(Routing.kt:586)
               at dev.programadorthi.routing.core.RoutingKt.routing(Routing.kt:555)
               at dev.programadorthi.routing.core.RoutingKt.routing$default(Routing.kt:531)
```

**Comment by programadorthi** [comment]
Upgrade applied to [2.0.0-alpha03](https://github.com/programadorthi/kotlin-routing/releases/tag/2.0.0-alpha03)
